/**
 * Generated by karavan build tools - do NOT edit this file!
 */
import { CamelElement } from "./IntegrationDefinition";
export declare class ProcessorDefinition extends CamelElement {
    idempotentConsumer?: IdempotentConsumerDefinition;
    resumable?: ResumableDefinition;
    doTry?: TryDefinition;
    convertBodyTo?: ConvertBodyDefinition | string;
    recipientList?: RecipientListDefinition;
    when?: WhenDefinition;
    setHeader?: SetHeaderDefinition;
    inOnly?: InOnlyDefinition | string;
    inOut?: InOutDefinition | string;
    split?: SplitDefinition;
    interceptSendToEndpoint?: InterceptSendToEndpointDefinition | string;
    loop?: LoopDefinition;
    setExchangePattern?: SetExchangePatternDefinition | string;
    marshal?: MarshalDefinition;
    onFallback?: OnFallbackDefinition;
    circuitBreaker?: CircuitBreakerDefinition;
    enrich?: EnrichDefinition;
    kamelet?: KameletDefinition | string;
    saga?: SagaDefinition;
    bean?: BeanDefinition | string;
    otherwise?: OtherwiseDefinition;
    toD?: string;
    sort?: SortDefinition;
    loadBalance?: LoadBalanceDefinition;
    script?: ScriptDefinition;
    removeHeader?: RemoveHeaderDefinition | string;
    delay?: DelayDefinition;
    stop?: StopDefinition;
    serviceCall?: ServiceCallDefinition | string;
    intercept?: InterceptDefinition;
    whenSkipSendToEndpoint?: WhenSkipSendToEndpointDefinition;
    setProperty?: SetPropertyDefinition;
    removeProperty?: RemovePropertyDefinition | string;
    interceptFrom?: InterceptFromDefinition | string;
    onCompletion?: OnCompletionDefinition;
    pausable?: PausableDefinition;
    throttle?: ThrottleDefinition;
    doFinally?: FinallyDefinition;
    log?: LogDefinition | string;
    doCatch?: CatchDefinition;
    transacted?: TransactedDefinition;
    claimCheck?: ClaimCheckDefinition;
    pollEnrich?: PollEnrichDefinition;
    removeHeaders?: RemoveHeadersDefinition | string;
    aggregate?: AggregateDefinition;
    resequence?: ResequenceDefinition;
    routingSlip?: RoutingSlipDefinition | string;
    transform?: TransformDefinition;
    stepName?: string;
    removeProperties?: RemovePropertiesDefinition | string;
    policy?: PolicyDefinition;
    validate?: ValidateDefinition;
    rollback?: RollbackDefinition | string;
    process?: ProcessDefinition;
    threads?: ThreadsDefinition;
    setBody?: SetBodyDefinition;
    sample?: SamplingDefinition | string;
    throwException?: ThrowExceptionDefinition;
    dynamicRouter?: DynamicRouterDefinition;
    multicast?: MulticastDefinition;
    filter?: FilterDefinition;
    pipeline?: PipelineDefinition;
    unmarshal?: UnmarshalDefinition;
    wireTap?: WireTapDefinition;
    step?: StepDefinition;
    to?: string;
    choice?: ChoiceDefinition;
    constructor(init?: Partial<ProcessorDefinition>);
}
export declare class BeansDeserializer extends CamelElement {
    constructor(init?: Partial<BeansDeserializer>);
}
export declare class ErrorHandlerBuilderDeserializer extends CamelElement {
    deadLetterChannel?: DeadLetterChannelDefinition;
    ref?: string;
    log?: DefaultErrorHandlerDefinition;
    none?: NoErrorHandlerDefinition;
    constructor(init?: Partial<ErrorHandlerBuilderDeserializer>);
}
export declare class NamedBeanDefinition extends CamelElement {
    name: string;
    type: string;
    properties?: any;
    constructor(init?: Partial<NamedBeanDefinition>);
}
export declare class OutputAwareFromDefinition extends CamelElement {
    parameters?: any;
    steps: CamelElement[];
    uri: string;
    constructor(init?: Partial<OutputAwareFromDefinition>);
}
export declare class AggregateDefinition extends CamelElement {
    aggregationRepository?: string;
    aggregationStrategy: string;
    executorService?: string;
    closeCorrelationKeyOnCompletion?: number;
    description?: string;
    discardOnAggregationFailure?: boolean;
    eagerCheckCompletion?: boolean;
    correlationExpression?: ExpressionSubElementDefinition;
    timeoutCheckerExecutorService?: string;
    completionOnNewCorrelationGroup?: boolean;
    stepName?: string;
    completionInterval?: string;
    parallelProcessing?: boolean;
    id?: string;
    completionPredicate?: ExpressionSubElementDefinition;
    aggregationStrategyMethodAllowNull?: boolean;
    forceCompletionOnStop?: boolean;
    completionFromBatchConsumer?: boolean;
    completeAllOnStop?: boolean;
    completionSize?: number;
    optimisticLockRetryPolicy?: OptimisticLockRetryPolicyDefinition;
    aggregationStrategyMethodName?: string;
    steps?: CamelElement[];
    completionSizeExpression?: ExpressionSubElementDefinition;
    aggregateController?: string;
    completionTimeout?: string;
    completionTimeoutExpression?: ExpressionSubElementDefinition;
    inheritErrorHandler?: boolean;
    ignoreInvalidCorrelationKeys?: boolean;
    discardOnCompletionTimeout?: boolean;
    completionTimeoutCheckerInterval?: string;
    optimisticLocking?: boolean;
    constructor(init?: Partial<AggregateDefinition>);
}
export declare class BeanDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    ref?: string;
    method?: string;
    stepName?: string;
    scope?: string;
    description?: string;
    id?: string;
    beanType?: string;
    constructor(init?: Partial<BeanDefinition>);
}
export declare class CatchDefinition extends CamelElement {
    exception?: string[];
    inheritErrorHandler?: boolean;
    stepName?: string;
    onWhen?: WhenDefinition;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<CatchDefinition>);
}
export declare class ChoiceDefinition extends CamelElement {
    otherwise?: OtherwiseDefinition;
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    precondition?: boolean;
    when?: WhenDefinition[];
    constructor(init?: Partial<ChoiceDefinition>);
}
export declare class CircuitBreakerDefinition extends CamelElement {
    faultToleranceConfiguration?: FaultToleranceConfigurationDefinition;
    inheritErrorHandler?: boolean;
    stepName?: string;
    configuration?: string;
    resilience4jConfiguration?: Resilience4jConfigurationDefinition;
    onFallback?: OnFallbackDefinition;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<CircuitBreakerDefinition>);
}
export declare class ClaimCheckDefinition extends CamelElement {
    filter?: string;
    inheritErrorHandler?: boolean;
    aggregationStrategy?: string;
    stepName?: string;
    description?: string;
    id?: string;
    aggregationStrategyMethodName?: string;
    operation: string;
    key?: string;
    constructor(init?: Partial<ClaimCheckDefinition>);
}
export declare class ContextScanDefinition extends CamelElement {
    excludes?: string[];
    stepName?: string;
    includeNonSingletons?: boolean;
    includes?: string[];
    constructor(init?: Partial<ContextScanDefinition>);
}
export declare class ConvertBodyDefinition extends CamelElement {
    charset?: string;
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    type: string;
    mandatory?: boolean;
    constructor(init?: Partial<ConvertBodyDefinition>);
}
export declare class DataFormatDefinition extends CamelElement {
    stepName?: string;
    id?: string;
    constructor(init?: Partial<DataFormatDefinition>);
}
export declare class DelayDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    callerRunsWhenRejected?: boolean;
    executorService?: string;
    asyncDelayed?: boolean;
    description?: string;
    id?: string;
    constructor(init?: Partial<DelayDefinition>);
}
export declare class DescriptionDefinition extends CamelElement {
    stepName?: string;
    text?: string;
    lang?: string;
    constructor(init?: Partial<DescriptionDefinition>);
}
export declare class DynamicRouterDefinition extends CamelElement {
    uriDelimiter?: string;
    ignoreInvalidEndpoints?: boolean;
    inheritErrorHandler?: boolean;
    cacheSize?: number;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<DynamicRouterDefinition>);
}
export declare class EnrichDefinition extends CamelElement {
    aggregationStrategy?: string;
    cacheSize?: number;
    expression?: ExpressionDefinition;
    description?: string;
    allowOptimisedComponents?: boolean;
    aggregationStrategyMethodName?: string;
    inheritErrorHandler?: boolean;
    stepName?: string;
    ignoreInvalidEndpoint?: boolean;
    id?: string;
    aggregateOnException?: boolean;
    aggregationStrategyMethodAllowNull?: string;
    shareUnitOfWork?: boolean;
    constructor(init?: Partial<EnrichDefinition>);
}
export declare class ErrorHandlerDefinition extends CamelElement {
    deadLetterChannel?: DeadLetterChannelDefinition;
    noErrorHandler?: NoErrorHandlerDefinition;
    stepName?: string;
    jtaTransactionErrorHandler?: JtaTransactionErrorHandlerDefinition;
    defaultErrorHandler?: DefaultErrorHandlerDefinition;
    springTransactionErrorHandler?: SpringTransactionErrorHandlerDefinition;
    id?: string;
    constructor(init?: Partial<ErrorHandlerDefinition>);
}
export declare class ExpressionSubElementDefinition extends CamelElement {
    ognl?: OgnlExpression | string;
    constant?: ConstantExpression | string;
    mvel?: MvelExpression | string;
    method?: MethodCallExpression | string;
    xquery?: XQueryExpression | string;
    datasonnet?: DatasonnetExpression | string;
    jq?: JqExpression | string;
    language?: LanguageExpression;
    simple?: SimpleExpression | string;
    hl7terser?: Hl7TerserExpression | string;
    tokenize?: TokenizerExpression | string;
    spel?: SpELExpression | string;
    ref?: RefExpression | string;
    xpath?: XPathExpression | string;
    groovy?: GroovyExpression | string;
    csimple?: CSimpleExpression | string;
    stepName?: string;
    exchangeProperty?: ExchangePropertyExpression | string;
    jsonpath?: JsonPathExpression | string;
    header?: HeaderExpression | string;
    joor?: JoorExpression | string;
    xtokenize?: XMLTokenizerExpression | string;
    constructor(init?: Partial<ExpressionSubElementDefinition>);
}
export declare class FaultToleranceConfigurationDefinition extends CamelElement {
    failureRatio?: number;
    timeoutDuration?: string;
    timeoutEnabled?: boolean;
    timeoutScheduledExecutorService?: string;
    successThreshold?: number;
    timeoutPoolSize?: number;
    requestVolumeThreshold?: number;
    bulkheadExecutorService?: string;
    delay?: string;
    stepName?: string;
    bulkheadWaitingTaskQueue?: number;
    circuitBreaker?: string;
    id?: string;
    bulkheadMaxConcurrentCalls?: number;
    bulkheadEnabled?: boolean;
    constructor(init?: Partial<FaultToleranceConfigurationDefinition>);
}
export declare class FilterDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    statusPropertyName?: string;
    constructor(init?: Partial<FilterDefinition>);
}
export declare class FinallyDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<FinallyDefinition>);
}
export declare class FromDefinition extends CamelElement {
    stepName?: string;
    parameters?: any;
    steps: CamelElement[];
    uri: string;
    constructor(init?: Partial<FromDefinition>);
}
export declare class GlobalOptionDefinition extends CamelElement {
    stepName?: string;
    value: string;
    key: string;
    constructor(init?: Partial<GlobalOptionDefinition>);
}
export declare class GlobalOptionsDefinition extends CamelElement {
    stepName?: string;
    globalOption?: GlobalOptionDefinition[];
    constructor(init?: Partial<GlobalOptionsDefinition>);
}
export declare class IdempotentConsumerDefinition extends CamelElement {
    completionEager?: boolean;
    skipDuplicate?: boolean;
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    eager?: boolean;
    stepName?: string;
    idempotentRepository: string;
    description?: string;
    removeOnFailure?: boolean;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<IdempotentConsumerDefinition>);
}
export declare class InOnlyDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    parameters?: any;
    uri: string;
    constructor(init?: Partial<InOnlyDefinition>);
}
export declare class InOutDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    parameters?: any;
    uri: string;
    constructor(init?: Partial<InOutDefinition>);
}
export declare class InputTypeDefinition extends CamelElement {
    urn: string;
    stepName?: string;
    description?: string;
    id?: string;
    validate?: boolean;
    constructor(init?: Partial<InputTypeDefinition>);
}
export declare class InterceptDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<InterceptDefinition>);
}
export declare class InterceptFromDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    uri?: string;
    constructor(init?: Partial<InterceptFromDefinition>);
}
export declare class InterceptSendToEndpointDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    afterUri?: string;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    uri: string;
    skipSendToOriginalEndpoint?: string;
    constructor(init?: Partial<InterceptSendToEndpointDefinition>);
}
export declare class KameletDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    name: string;
    parameters?: any;
    constructor(init?: Partial<KameletDefinition>);
}
export declare class LoadBalanceDefinition extends CamelElement {
    random?: RandomLoadBalancerDefinition;
    inheritErrorHandler?: boolean;
    customLoadBalancer?: CustomLoadBalancerDefinition | string;
    stepName?: string;
    failover?: FailoverLoadBalancerDefinition;
    sticky?: StickyLoadBalancerDefinition;
    description?: string;
    topic?: TopicLoadBalancerDefinition;
    id?: string;
    steps?: CamelElement[];
    weighted?: WeightedLoadBalancerDefinition;
    roundRobin?: RoundRobinLoadBalancerDefinition;
    constructor(init?: Partial<LoadBalanceDefinition>);
}
export declare class LogDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    logName?: string;
    stepName?: string;
    marker?: string;
    logger?: string;
    description?: string;
    id?: string;
    message: string;
    loggingLevel?: string;
    constructor(init?: Partial<LogDefinition>);
}
export declare class LoopDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    doWhile?: boolean;
    description?: string;
    breakOnShutdown?: boolean;
    copy?: boolean;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<LoopDefinition>);
}
export declare class MarshalDefinition extends CamelElement {
    univocityCsv?: UniVocityCsvDataFormat;
    protobuf?: ProtobufDataFormat | string;
    tarFile?: TarFileDataFormat;
    tidyMarkup?: TidyMarkupDataFormat;
    csv?: CsvDataFormat | string;
    base64?: Base64DataFormat;
    zipDeflater?: ZipDeflaterDataFormat;
    description?: string;
    bindy?: BindyDataFormat;
    syslog?: SyslogDataFormat;
    zipFile?: ZipFileDataFormat;
    jaxb?: JaxbDataFormat;
    rss?: RssDataFormat;
    stepName?: string;
    mimeMultipart?: MimeMultipartDataFormat;
    asn1?: ASN1DataFormat | string;
    pgp?: PGPDataFormat;
    thrift?: ThriftDataFormat | string;
    json?: JsonDataFormat;
    lzf?: LZFDataFormat;
    id?: string;
    fhirXml?: FhirXmlDataFormat;
    barcode?: BarcodeDataFormat;
    avro?: AvroDataFormat | string;
    yaml?: YAMLDataFormat;
    fhirJson?: FhirJsonDataFormat;
    any23?: Any23DataFormat | string;
    custom?: CustomDataFormat | string;
    flatpack?: FlatpackDataFormat;
    cbor?: CBORDataFormat;
    crypto?: CryptoDataFormat;
    univocityTsv?: UniVocityTsvDataFormat;
    hl7?: HL7DataFormat;
    inheritErrorHandler?: boolean;
    jsonApi?: JsonApiDataFormat;
    xmlSecurity?: XMLSecurityDataFormat;
    ical?: IcalDataFormat;
    univocityFixed?: UniVocityFixedDataFormat;
    jacksonXml?: JacksonXMLDataFormat;
    grok?: GrokDataFormat;
    xstream?: XStreamDataFormat | string;
    gzipDeflater?: GzipDeflaterDataFormat;
    soap?: SoapDataFormat | string;
    constructor(init?: Partial<MarshalDefinition>);
}
export declare class MulticastDefinition extends CamelElement {
    aggregationStrategy?: string;
    onPrepare?: string;
    executorService?: string;
    description?: string;
    aggregationStrategyMethodName?: string;
    steps?: CamelElement[];
    timeout?: string;
    inheritErrorHandler?: boolean;
    streaming?: boolean;
    stepName?: string;
    stopOnException?: boolean;
    parallelProcessing?: boolean;
    id?: string;
    parallelAggregate?: boolean;
    aggregationStrategyMethodAllowNull?: boolean;
    shareUnitOfWork?: boolean;
    constructor(init?: Partial<MulticastDefinition>);
}
export declare class OnCompletionDefinition extends CamelElement {
    mode?: string;
    inheritErrorHandler?: boolean;
    onCompleteOnly?: boolean;
    stepName?: string;
    executorService?: string;
    parallelProcessing?: boolean;
    onWhen?: WhenDefinition;
    description?: string;
    id?: string;
    useOriginalMessage?: boolean;
    steps?: CamelElement[];
    onFailureOnly?: boolean;
    constructor(init?: Partial<OnCompletionDefinition>);
}
export declare class OnExceptionDefinition extends CamelElement {
    exception?: string[];
    redeliveryPolicy?: RedeliveryPolicyDefinition;
    continued?: ExpressionSubElementDefinition;
    description?: string;
    useOriginalMessage?: boolean;
    steps?: CamelElement[];
    retryWhile?: ExpressionSubElementDefinition;
    inheritErrorHandler?: boolean;
    onRedeliveryRef?: string;
    stepName?: string;
    useOriginalBody?: boolean;
    handled?: ExpressionSubElementDefinition;
    onWhen?: WhenDefinition;
    id?: string;
    onExceptionOccurredRef?: string;
    redeliveryPolicyRef?: string;
    constructor(init?: Partial<OnExceptionDefinition>);
}
export declare class OnFallbackDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    fallbackViaNetwork?: boolean;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<OnFallbackDefinition>);
}
export declare class OptimisticLockRetryPolicyDefinition extends CamelElement {
    retryDelay?: string;
    stepName?: string;
    maximumRetries?: number;
    randomBackOff?: boolean;
    exponentialBackOff?: boolean;
    maximumRetryDelay?: string;
    constructor(init?: Partial<OptimisticLockRetryPolicyDefinition>);
}
export declare class OtherwiseDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<OtherwiseDefinition>);
}
export declare class OutputDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<OutputDefinition>);
}
export declare class OutputTypeDefinition extends CamelElement {
    urn: string;
    stepName?: string;
    description?: string;
    id?: string;
    validate?: boolean;
    constructor(init?: Partial<OutputTypeDefinition>);
}
export declare class PackageScanDefinition extends CamelElement {
    excludes?: string[];
    package?: string[];
    stepName?: string;
    includes?: string[];
    constructor(init?: Partial<PackageScanDefinition>);
}
export declare class PausableDefinition extends CamelElement {
    untilCheck: string;
    inheritErrorHandler?: boolean;
    stepName?: string;
    consumerListener: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<PausableDefinition>);
}
export declare class PipelineDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<PipelineDefinition>);
}
export declare class PolicyDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    ref: string;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<PolicyDefinition>);
}
export declare class PollEnrichDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    aggregationStrategy?: string;
    cacheSize?: number;
    expression?: ExpressionDefinition;
    stepName?: string;
    ignoreInvalidEndpoint?: boolean;
    description?: string;
    id?: string;
    aggregateOnException?: boolean;
    aggregationStrategyMethodName?: string;
    timeout?: string;
    aggregationStrategyMethodAllowNull?: string;
    constructor(init?: Partial<PollEnrichDefinition>);
}
export declare class ProcessDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    ref: string;
    stepName?: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<ProcessDefinition>);
}
export declare class PropertyDefinition extends CamelElement {
    stepName?: string;
    value: string;
    key: string;
    constructor(init?: Partial<PropertyDefinition>);
}
export declare class PropertyExpressionDefinition extends CamelElement {
    expression?: ExpressionDefinition;
    stepName?: string;
    key: string;
    constructor(init?: Partial<PropertyExpressionDefinition>);
}
export declare class RecipientListDefinition extends CamelElement {
    aggregationStrategy?: string;
    cacheSize?: number;
    expression?: ExpressionDefinition;
    onPrepare?: string;
    executorService?: string;
    description?: string;
    aggregationStrategyMethodName?: string;
    timeout?: string;
    ignoreInvalidEndpoints?: boolean;
    inheritErrorHandler?: boolean;
    streaming?: boolean;
    stepName?: string;
    stopOnException?: boolean;
    delimiter?: string;
    parallelProcessing?: boolean;
    id?: string;
    parallelAggregate?: boolean;
    aggregationStrategyMethodAllowNull?: boolean;
    shareUnitOfWork?: boolean;
    constructor(init?: Partial<RecipientListDefinition>);
}
export declare class RedeliveryPolicyDefinition extends CamelElement {
    logNewException?: boolean;
    backOffMultiplier?: number;
    delayPattern?: string;
    retryAttemptedLogInterval?: number;
    logRetryAttempted?: boolean;
    logExhaustedMessageHistory?: boolean;
    stepName?: string;
    collisionAvoidanceFactor?: number;
    logRetryStackTrace?: boolean;
    disableRedelivery?: boolean;
    id?: string;
    logExhaustedMessageBody?: boolean;
    logHandled?: boolean;
    useCollisionAvoidance?: boolean;
    exchangeFormatterRef?: string;
    allowRedeliveryWhileStopping?: boolean;
    retriesExhaustedLogLevel?: string;
    logStackTrace?: boolean;
    maximumRedeliveryDelay?: string;
    useExponentialBackOff?: boolean;
    asyncDelayedRedelivery?: boolean;
    logContinued?: boolean;
    retryAttemptedLogLevel?: string;
    redeliveryDelay?: string;
    maximumRedeliveries?: number;
    logExhausted?: boolean;
    constructor(init?: Partial<RedeliveryPolicyDefinition>);
}
export declare class RemoveHeaderDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    name: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<RemoveHeaderDefinition>);
}
export declare class RemoveHeadersDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    excludePattern?: string;
    pattern: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<RemoveHeadersDefinition>);
}
export declare class RemovePropertiesDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    excludePattern?: string;
    pattern: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<RemovePropertiesDefinition>);
}
export declare class RemovePropertyDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    name: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<RemovePropertyDefinition>);
}
export declare class ResequenceDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    streamConfig?: StreamResequencerConfig;
    expression: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    batchConfig?: BatchResequencerConfig;
    constructor(init?: Partial<ResequenceDefinition>);
}
export declare class Resilience4jConfigurationDefinition extends CamelElement {
    failureRateThreshold?: number;
    slowCallDurationThreshold?: number;
    minimumNumberOfCalls?: number;
    permittedNumberOfCallsInHalfOpenState?: number;
    slowCallRateThreshold?: number;
    stepName?: string;
    writableStackTraceEnabled?: boolean;
    automaticTransitionFromOpenToHalfOpenEnabled?: boolean;
    circuitBreaker?: string;
    slidingWindowSize?: number;
    id?: string;
    config?: string;
    slidingWindowType?: string;
    waitDurationInOpenState?: number;
    constructor(init?: Partial<Resilience4jConfigurationDefinition>);
}
export declare class RestContextRefDefinition extends CamelElement {
    ref: string;
    stepName?: string;
    constructor(init?: Partial<RestContextRefDefinition>);
}
export declare class ResumableDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    resumeStrategy: string;
    intermittent?: boolean;
    description?: string;
    id?: string;
    constructor(init?: Partial<ResumableDefinition>);
}
export declare class RollbackDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    markRollbackOnly?: boolean;
    description?: string;
    id?: string;
    message?: string;
    markRollbackOnlyLast?: boolean;
    constructor(init?: Partial<RollbackDefinition>);
}
export declare class RouteBuilderDefinition extends CamelElement {
    ref: string;
    stepName?: string;
    id?: string;
    constructor(init?: Partial<RouteBuilderDefinition>);
}
export declare class RouteConfigurationContextRefDefinition extends CamelElement {
    ref: string;
    stepName?: string;
    constructor(init?: Partial<RouteConfigurationContextRefDefinition>);
}
export declare class RouteConfigurationDefinition extends CamelElement {
    onCompletion?: OnCompletionDefinition[];
    interceptSendToEndpoint?: InterceptSendToEndpointDefinition[];
    stepName?: string;
    intercept?: InterceptDefinition[];
    errorHandler?: ErrorHandlerDefinition;
    onException?: OnExceptionDefinition[];
    id?: string;
    precondition?: string;
    interceptFrom?: InterceptFromDefinition[];
    constructor(init?: Partial<RouteConfigurationDefinition>);
}
export declare class RouteContextRefDefinition extends CamelElement {
    ref: string;
    stepName?: string;
    constructor(init?: Partial<RouteContextRefDefinition>);
}
export declare class RouteDefinition extends CamelElement {
    stepName?: string;
    routeConfigurationId?: string;
    description?: string;
    from: FromDefinition;
    streamCaching?: boolean;
    id?: string;
    precondition?: string;
    autoStartup?: boolean;
    group?: string;
    constructor(init?: Partial<RouteDefinition>);
}
export declare class RouteTemplateBeanDefinition extends CamelElement {
    stepName?: string;
    name: string;
    property?: PropertyDefinition[];
    type: string;
    beanType?: string;
    properties?: any;
    script?: string;
    constructor(init?: Partial<RouteTemplateBeanDefinition>);
}
export declare class RouteTemplateDefinition extends CamelElement {
    stepName?: string;
    beans?: NamedBeanDefinition[];
    from: FromDefinition;
    id: string;
    parameters?: RouteTemplateParameterDefinition[];
    constructor(init?: Partial<RouteTemplateDefinition>);
}
export declare class RouteTemplateParameterDefinition extends CamelElement {
    stepName?: string;
    defaultValue?: string;
    name: string;
    description?: string;
    required?: boolean;
    constructor(init?: Partial<RouteTemplateParameterDefinition>);
}
export declare class RoutingSlipDefinition extends CamelElement {
    uriDelimiter?: string;
    ignoreInvalidEndpoints?: boolean;
    inheritErrorHandler?: boolean;
    cacheSize?: number;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<RoutingSlipDefinition>);
}
export declare class SagaActionUriDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    parameters?: any;
    uri: string;
    constructor(init?: Partial<SagaActionUriDefinition>);
}
export declare class SagaDefinition extends CamelElement {
    completion?: string;
    inheritErrorHandler?: boolean;
    propagation?: string;
    stepName?: string;
    description?: string;
    compensation?: string;
    completionMode?: string;
    sagaService?: string;
    id?: string;
    steps?: CamelElement[];
    timeout?: string;
    option?: PropertyExpressionDefinition[];
    constructor(init?: Partial<SagaDefinition>);
}
export declare class SamplingDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    messageFrequency?: number;
    id?: string;
    samplePeriod?: string;
    constructor(init?: Partial<SamplingDefinition>);
}
export declare class ScriptDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<ScriptDefinition>);
}
export declare class SetBodyDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<SetBodyDefinition>);
}
export declare class SetExchangePatternDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    pattern: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<SetExchangePatternDefinition>);
}
export declare class SetHeaderDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    name: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<SetHeaderDefinition>);
}
export declare class SetPropertyDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    name: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<SetPropertyDefinition>);
}
export declare class SortDefinition extends CamelElement {
    comparator?: string;
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<SortDefinition>);
}
export declare class SplitDefinition extends CamelElement {
    aggregationStrategy?: string;
    expression?: ExpressionDefinition;
    onPrepare?: string;
    executorService?: string;
    description?: string;
    aggregationStrategyMethodName?: string;
    steps?: CamelElement[];
    timeout?: string;
    inheritErrorHandler?: boolean;
    streaming?: boolean;
    stepName?: string;
    stopOnException?: boolean;
    delimiter?: string;
    parallelProcessing?: boolean;
    id?: string;
    parallelAggregate?: boolean;
    aggregationStrategyMethodAllowNull?: boolean;
    shareUnitOfWork?: boolean;
    constructor(init?: Partial<SplitDefinition>);
}
export declare class StepDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<StepDefinition>);
}
export declare class StopDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<StopDefinition>);
}
export declare class TemplatedRouteBeanDefinition extends CamelElement {
    stepName?: string;
    name: string;
    property?: PropertyDefinition[];
    type: string;
    beanType?: string;
    properties?: any;
    script?: string;
    constructor(init?: Partial<TemplatedRouteBeanDefinition>);
}
export declare class TemplatedRouteDefinition extends CamelElement {
    routeId?: string;
    stepName?: string;
    beans?: NamedBeanDefinition[];
    parameters?: TemplatedRouteParameterDefinition[];
    routeTemplateRef: string;
    constructor(init?: Partial<TemplatedRouteDefinition>);
}
export declare class TemplatedRouteParameterDefinition extends CamelElement {
    stepName?: string;
    name: string;
    value: string;
    constructor(init?: Partial<TemplatedRouteParameterDefinition>);
}
export declare class ThreadPoolProfileDefinition extends CamelElement {
    keepAliveTime?: number;
    stepName?: string;
    maxQueueSize?: number;
    allowCoreThreadTimeOut?: boolean;
    poolSize?: number;
    description?: string;
    defaultProfile?: boolean;
    id?: string;
    maxPoolSize?: number;
    rejectedPolicy?: string;
    timeUnit?: string;
    constructor(init?: Partial<ThreadPoolProfileDefinition>);
}
export declare class ThreadsDefinition extends CamelElement {
    keepAliveTime?: number;
    callerRunsWhenRejected?: string;
    executorService?: string;
    poolSize?: number;
    description?: string;
    threadName?: string;
    rejectedPolicy?: string;
    inheritErrorHandler?: boolean;
    stepName?: string;
    maxQueueSize?: number;
    allowCoreThreadTimeOut?: boolean;
    id?: string;
    maxPoolSize?: number;
    timeUnit?: string;
    constructor(init?: Partial<ThreadsDefinition>);
}
export declare class ThrottleDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    callerRunsWhenRejected?: boolean;
    executorService?: string;
    timePeriodMillis?: string;
    asyncDelayed?: boolean;
    description?: string;
    rejectExecution?: boolean;
    correlationExpression?: ExpressionSubElementDefinition;
    id?: string;
    constructor(init?: Partial<ThrottleDefinition>);
}
export declare class ThrowExceptionDefinition extends CamelElement {
    exceptionType?: string;
    inheritErrorHandler?: boolean;
    ref?: string;
    stepName?: string;
    description?: string;
    id?: string;
    message?: string;
    constructor(init?: Partial<ThrowExceptionDefinition>);
}
export declare class ToDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    stepName?: string;
    pattern?: string;
    description?: string;
    id?: string;
    parameters?: any;
    uri: string;
    constructor(init?: Partial<ToDefinition>);
}
export declare class ToDynamicDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    cacheSize?: number;
    stepName?: string;
    ignoreInvalidEndpoint?: boolean;
    autoStartComponents?: boolean;
    pattern?: string;
    description?: string;
    id?: string;
    allowOptimisedComponents?: boolean;
    parameters?: any;
    uri: string;
    constructor(init?: Partial<ToDynamicDefinition>);
}
export declare class TransactedDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    ref?: string;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<TransactedDefinition>);
}
export declare class TransformDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<TransformDefinition>);
}
export declare class TryDefinition extends CamelElement {
    doFinally?: FinallyDefinition;
    inheritErrorHandler?: boolean;
    stepName?: string;
    doCatch?: CatchDefinition[];
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<TryDefinition>);
}
export declare class UnmarshalDefinition extends CamelElement {
    univocityCsv?: UniVocityCsvDataFormat;
    protobuf?: ProtobufDataFormat | string;
    tarFile?: TarFileDataFormat;
    tidyMarkup?: TidyMarkupDataFormat;
    csv?: CsvDataFormat | string;
    base64?: Base64DataFormat;
    zipDeflater?: ZipDeflaterDataFormat;
    description?: string;
    bindy?: BindyDataFormat;
    syslog?: SyslogDataFormat;
    zipFile?: ZipFileDataFormat;
    jaxb?: JaxbDataFormat;
    rss?: RssDataFormat;
    stepName?: string;
    mimeMultipart?: MimeMultipartDataFormat;
    asn1?: ASN1DataFormat | string;
    pgp?: PGPDataFormat;
    thrift?: ThriftDataFormat | string;
    json?: JsonDataFormat;
    lzf?: LZFDataFormat;
    id?: string;
    fhirXml?: FhirXmlDataFormat;
    barcode?: BarcodeDataFormat;
    allowNullBody?: boolean;
    avro?: AvroDataFormat | string;
    yaml?: YAMLDataFormat;
    fhirJson?: FhirJsonDataFormat;
    any23?: Any23DataFormat | string;
    custom?: CustomDataFormat | string;
    flatpack?: FlatpackDataFormat;
    cbor?: CBORDataFormat;
    crypto?: CryptoDataFormat;
    univocityTsv?: UniVocityTsvDataFormat;
    hl7?: HL7DataFormat;
    inheritErrorHandler?: boolean;
    jsonApi?: JsonApiDataFormat;
    xmlSecurity?: XMLSecurityDataFormat;
    ical?: IcalDataFormat;
    univocityFixed?: UniVocityFixedDataFormat;
    jacksonXml?: JacksonXMLDataFormat;
    grok?: GrokDataFormat;
    xstream?: XStreamDataFormat | string;
    gzipDeflater?: GzipDeflaterDataFormat;
    soap?: SoapDataFormat | string;
    constructor(init?: Partial<UnmarshalDefinition>);
}
export declare class ValidateDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    predicateExceptionFactory?: string;
    constructor(init?: Partial<ValidateDefinition>);
}
export declare class WhenDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<WhenDefinition>);
}
export declare class WhenSkipSendToEndpointDefinition extends CamelElement {
    inheritErrorHandler?: boolean;
    expression?: ExpressionDefinition;
    stepName?: string;
    description?: string;
    id?: string;
    steps?: CamelElement[];
    constructor(init?: Partial<WhenSkipSendToEndpointDefinition>);
}
export declare class WireTapDefinition extends CamelElement {
    cacheSize?: number;
    onPrepare?: string;
    executorService?: string;
    pattern?: string;
    description?: string;
    allowOptimisedComponents?: boolean;
    uri: string;
    dynamicUri?: boolean;
    inheritErrorHandler?: boolean;
    stepName?: string;
    ignoreInvalidEndpoint?: boolean;
    autoStartComponents?: boolean;
    copy?: boolean;
    id?: string;
    parameters?: any;
    constructor(init?: Partial<WireTapDefinition>);
}
export declare class BlacklistServiceCallServiceFilterConfiguration extends CamelElement {
    servers?: string[];
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<BlacklistServiceCallServiceFilterConfiguration>);
}
export declare class CachingServiceCallServiceDiscoveryConfiguration extends CamelElement {
    dnsServiceDiscovery?: DnsServiceCallServiceDiscoveryConfiguration;
    kubernetesServiceDiscovery?: KubernetesServiceCallServiceDiscoveryConfiguration;
    consulServiceDiscovery?: ConsulServiceCallServiceDiscoveryConfiguration;
    id?: string;
    units?: string;
    staticServiceDiscovery?: StaticServiceCallServiceDiscoveryConfiguration;
    combinedServiceDiscovery?: CombinedServiceCallServiceDiscoveryConfiguration;
    properties?: PropertyDefinition[];
    timeout?: number;
    constructor(init?: Partial<CachingServiceCallServiceDiscoveryConfiguration>);
}
export declare class CombinedServiceCallServiceDiscoveryConfiguration extends CamelElement {
    cachingServiceDiscovery?: CachingServiceCallServiceDiscoveryConfiguration;
    dnsServiceDiscovery?: DnsServiceCallServiceDiscoveryConfiguration;
    kubernetesServiceDiscovery?: KubernetesServiceCallServiceDiscoveryConfiguration;
    consulServiceDiscovery?: ConsulServiceCallServiceDiscoveryConfiguration;
    id?: string;
    staticServiceDiscovery?: StaticServiceCallServiceDiscoveryConfiguration;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<CombinedServiceCallServiceDiscoveryConfiguration>);
}
export declare class CombinedServiceCallServiceFilterConfiguration extends CamelElement {
    blacklistServiceFilter?: BlacklistServiceCallServiceFilterConfiguration;
    passThroughServiceFilter?: PassThroughServiceCallServiceFilterConfiguration;
    healthyServiceFilter?: HealthyServiceCallServiceFilterConfiguration;
    customServiceFilter?: CustomServiceCallServiceFilterConfiguration;
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<CombinedServiceCallServiceFilterConfiguration>);
}
export declare class ConsulServiceCallServiceDiscoveryConfiguration extends CamelElement {
    password?: string;
    aclToken?: string;
    readTimeoutMillis?: number;
    connectTimeoutMillis?: number;
    datacenter?: string;
    writeTimeoutMillis?: number;
    id?: string;
    userName?: string;
    blockSeconds?: number;
    properties?: PropertyDefinition[];
    url?: string;
    constructor(init?: Partial<ConsulServiceCallServiceDiscoveryConfiguration>);
}
export declare class CustomServiceCallServiceFilterConfiguration extends CamelElement {
    ref?: string;
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<CustomServiceCallServiceFilterConfiguration>);
}
export declare class DefaultServiceCallServiceLoadBalancerConfiguration extends CamelElement {
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<DefaultServiceCallServiceLoadBalancerConfiguration>);
}
export declare class DnsServiceCallServiceDiscoveryConfiguration extends CamelElement {
    domain?: string;
    proto?: string;
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<DnsServiceCallServiceDiscoveryConfiguration>);
}
export declare class HealthyServiceCallServiceFilterConfiguration extends CamelElement {
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<HealthyServiceCallServiceFilterConfiguration>);
}
export declare class KubernetesServiceCallServiceDiscoveryConfiguration extends CamelElement {
    lookup?: string;
    portProtocol?: string;
    caCertData?: string;
    portName?: string;
    oauthToken?: string;
    clientKeyAlgo?: string;
    clientCertFile?: string;
    dnsDomain?: string;
    password?: string;
    apiVersion?: string;
    clientKeyData?: string;
    masterUrl?: string;
    namespace?: string;
    clientCertData?: string;
    caCertFile?: string;
    clientKeyFile?: string;
    id?: string;
    clientKeyPassphrase?: string;
    properties?: PropertyDefinition[];
    trustCerts?: boolean;
    username?: string;
    constructor(init?: Partial<KubernetesServiceCallServiceDiscoveryConfiguration>);
}
export declare class PassThroughServiceCallServiceFilterConfiguration extends CamelElement {
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<PassThroughServiceCallServiceFilterConfiguration>);
}
export declare class ServiceCallConfigurationDefinition extends CamelElement {
    defaultLoadBalancer?: DefaultServiceCallServiceLoadBalancerConfiguration;
    serviceDiscoveryRef?: string;
    expression?: ServiceCallExpressionConfiguration;
    kubernetesServiceDiscovery?: KubernetesServiceCallServiceDiscoveryConfiguration;
    pattern?: string;
    customServiceFilter?: CustomServiceCallServiceFilterConfiguration;
    zookeeperServiceDiscovery?: ZooKeeperServiceCallServiceDiscoveryConfiguration;
    uri?: string;
    blacklistServiceFilter?: BlacklistServiceCallServiceFilterConfiguration;
    component?: string;
    expressionRef?: string;
    passThroughServiceFilter?: PassThroughServiceCallServiceFilterConfiguration;
    cachingServiceDiscovery?: CachingServiceCallServiceDiscoveryConfiguration;
    dnsServiceDiscovery?: DnsServiceCallServiceDiscoveryConfiguration;
    healthyServiceFilter?: HealthyServiceCallServiceFilterConfiguration;
    stepName?: string;
    loadBalancerRef?: string;
    serviceFilterRef?: string;
    combinedServiceFilter?: CombinedServiceCallServiceFilterConfiguration;
    serviceChooserRef?: string;
    consulServiceDiscovery?: ConsulServiceCallServiceDiscoveryConfiguration;
    id?: string;
    staticServiceDiscovery?: StaticServiceCallServiceDiscoveryConfiguration;
    combinedServiceDiscovery?: CombinedServiceCallServiceDiscoveryConfiguration;
    constructor(init?: Partial<ServiceCallConfigurationDefinition>);
}
export declare class ServiceCallDefinition extends CamelElement {
    pattern?: string;
    description?: string;
    blacklistServiceFilter?: BlacklistServiceCallServiceFilterConfiguration;
    expressionRef?: string;
    passThroughServiceFilter?: PassThroughServiceCallServiceFilterConfiguration;
    dnsServiceDiscovery?: DnsServiceCallServiceDiscoveryConfiguration;
    healthyServiceFilter?: HealthyServiceCallServiceFilterConfiguration;
    stepName?: string;
    serviceChooserRef?: string;
    consulServiceDiscovery?: ConsulServiceCallServiceDiscoveryConfiguration;
    id?: string;
    defaultLoadBalancer?: DefaultServiceCallServiceLoadBalancerConfiguration;
    serviceDiscoveryRef?: string;
    expression?: ServiceCallExpressionConfiguration;
    configurationRef?: string;
    kubernetesServiceDiscovery?: KubernetesServiceCallServiceDiscoveryConfiguration;
    customServiceFilter?: CustomServiceCallServiceFilterConfiguration;
    zookeeperServiceDiscovery?: ZooKeeperServiceCallServiceDiscoveryConfiguration;
    uri?: string;
    component?: string;
    inheritErrorHandler?: boolean;
    cachingServiceDiscovery?: CachingServiceCallServiceDiscoveryConfiguration;
    loadBalancerRef?: string;
    serviceFilterRef?: string;
    combinedServiceFilter?: CombinedServiceCallServiceFilterConfiguration;
    name: string;
    staticServiceDiscovery?: StaticServiceCallServiceDiscoveryConfiguration;
    combinedServiceDiscovery?: CombinedServiceCallServiceDiscoveryConfiguration;
    constructor(init?: Partial<ServiceCallDefinition>);
}
export declare class ServiceCallExpressionConfiguration extends CamelElement {
    hostHeader?: string;
    expressionType?: ExpressionDefinition;
    id?: string;
    portHeader?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<ServiceCallExpressionConfiguration>);
}
export declare class ServiceCallServiceChooserConfiguration extends CamelElement {
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<ServiceCallServiceChooserConfiguration>);
}
export declare class ServiceCallServiceDiscoveryConfiguration extends CamelElement {
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<ServiceCallServiceDiscoveryConfiguration>);
}
export declare class ServiceCallServiceFilterConfiguration extends CamelElement {
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<ServiceCallServiceFilterConfiguration>);
}
export declare class ServiceCallServiceLoadBalancerConfiguration extends CamelElement {
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<ServiceCallServiceLoadBalancerConfiguration>);
}
export declare class StaticServiceCallServiceDiscoveryConfiguration extends CamelElement {
    servers?: string[];
    id?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<StaticServiceCallServiceDiscoveryConfiguration>);
}
export declare class ZooKeeperServiceCallServiceDiscoveryConfiguration extends CamelElement {
    nodes: string;
    reconnectMaxRetries?: string;
    basePath: string;
    reconnectBaseSleepTime?: string;
    namespace?: string;
    reconnectMaxSleepTime?: string;
    sessionTimeout?: string;
    id?: string;
    connectionTimeout?: string;
    properties?: PropertyDefinition[];
    constructor(init?: Partial<ZooKeeperServiceCallServiceDiscoveryConfiguration>);
}
export declare class BatchResequencerConfig extends CamelElement {
    batchSize?: number;
    reverse?: boolean;
    allowDuplicates?: boolean;
    batchTimeout?: string;
    ignoreInvalidExchanges?: boolean;
    constructor(init?: Partial<BatchResequencerConfig>);
}
export declare class StreamResequencerConfig extends CamelElement {
    comparator?: string;
    timeout?: string;
    capacity?: number;
    deliveryAttemptInterval?: string;
    ignoreInvalidExchanges?: boolean;
    rejectOld?: boolean;
    constructor(init?: Partial<StreamResequencerConfig>);
}
export declare class ASN1DataFormat extends CamelElement {
    dataFormatName?: string;
    usingIterator?: boolean;
    id?: string;
    unmarshalType?: string;
    constructor(init?: Partial<ASN1DataFormat>);
}
export declare class Any23DataFormat extends CamelElement {
    extractors?: string[];
    configuration?: PropertyDefinition[];
    dataFormatName?: string;
    baseUri?: string;
    id?: string;
    outputFormat?: string;
    constructor(init?: Partial<Any23DataFormat>);
}
export declare class AvroDataFormat extends CamelElement {
    allowUnmarshallType?: boolean;
    include?: string;
    contentTypeHeader?: boolean;
    jsonView?: string;
    dataFormatName?: string;
    autoDiscoverSchemaResolver?: boolean;
    timezone?: string;
    instanceClassName?: string;
    moduleClassNames?: string;
    allowJmsType?: boolean;
    enableFeatures?: string;
    unmarshalType?: string;
    useList?: boolean;
    disableFeatures?: string;
    moduleRefs?: string;
    schemaResolver?: string;
    collectionType?: string;
    useDefaultObjectMapper?: boolean;
    library?: string;
    objectMapper?: string;
    autoDiscoverObjectMapper?: boolean;
    id?: string;
    constructor(init?: Partial<AvroDataFormat>);
}
export declare class BarcodeDataFormat extends CamelElement {
    barcodeFormat?: string;
    dataFormatName?: string;
    width?: number;
    id?: string;
    imageType?: string;
    height?: number;
    constructor(init?: Partial<BarcodeDataFormat>);
}
export declare class Base64DataFormat extends CamelElement {
    dataFormatName?: string;
    urlSafe?: boolean;
    id?: string;
    lineSeparator?: string;
    lineLength?: number;
    constructor(init?: Partial<Base64DataFormat>);
}
export declare class BindyDataFormat extends CamelElement {
    unwrapSingleInstance?: boolean;
    dataFormatName?: string;
    id?: string;
    locale?: string;
    type: string;
    allowEmptyStream?: boolean;
    classType?: string;
    constructor(init?: Partial<BindyDataFormat>);
}
export declare class CBORDataFormat extends CamelElement {
    allowUnmarshallType?: boolean;
    collectionType?: string;
    useDefaultObjectMapper?: boolean;
    objectMapper?: string;
    prettyPrint?: boolean;
    dataFormatName?: string;
    allowJmsType?: boolean;
    id?: string;
    enableFeatures?: string;
    unmarshalType?: string;
    useList?: boolean;
    disableFeatures?: string;
    constructor(init?: Partial<CBORDataFormat>);
}
export declare class CryptoDataFormat extends CamelElement {
    shouldAppendHmac?: boolean;
    inline?: boolean;
    macAlgorithm?: string;
    algorithmParameterRef?: string;
    dataFormatName?: string;
    cryptoProvider?: string;
    initVectorRef?: string;
    keyRef?: string;
    id?: string;
    algorithm?: string;
    bufferSize?: number;
    constructor(init?: Partial<CryptoDataFormat>);
}
export declare class CsvDataFormat extends CamelElement {
    escapeDisabled?: boolean;
    ignoreEmptyLines?: boolean;
    recordConverterRef?: string;
    trailingDelimiter?: boolean;
    headerDisabled?: boolean;
    lazyLoad?: boolean;
    commentMarkerDisabled?: boolean;
    skipHeaderRecord?: boolean;
    quote?: string;
    trim?: boolean;
    useMaps?: boolean;
    delimiter?: string;
    nullString?: string;
    allowMissingColumnNames?: boolean;
    id?: string;
    escape?: string;
    nullStringDisabled?: boolean;
    commentMarker?: string;
    dataFormatName?: string;
    formatRef?: string;
    quoteMode?: string;
    formatName?: string;
    ignoreSurroundingSpaces?: boolean;
    quoteDisabled?: boolean;
    useOrderedMaps?: boolean;
    header?: string[];
    ignoreHeaderCase?: boolean;
    recordSeparatorDisabled?: string;
    captureHeaderRecord?: boolean;
    marshallerFactoryRef?: string;
    recordSeparator?: string;
    constructor(init?: Partial<CsvDataFormat>);
}
export declare class CustomDataFormat extends CamelElement {
    ref: string;
    dataFormatName?: string;
    id?: string;
    constructor(init?: Partial<CustomDataFormat>);
}
export declare class DataFormatsDefinition extends CamelElement {
    univocityCsv?: UniVocityCsvDataFormat;
    protobuf?: ProtobufDataFormat | string;
    tarFile?: TarFileDataFormat;
    tidyMarkup?: TidyMarkupDataFormat;
    csv?: CsvDataFormat | string;
    base64?: Base64DataFormat;
    zipDeflater?: ZipDeflaterDataFormat;
    bindy?: BindyDataFormat;
    syslog?: SyslogDataFormat;
    zipFile?: ZipFileDataFormat;
    jaxb?: JaxbDataFormat;
    rss?: RssDataFormat;
    stepName?: string;
    mimeMultipart?: MimeMultipartDataFormat;
    asn1?: ASN1DataFormat | string;
    pgp?: PGPDataFormat;
    thrift?: ThriftDataFormat | string;
    json?: JsonDataFormat;
    lzf?: LZFDataFormat;
    fhirXml?: FhirXmlDataFormat;
    barcode?: BarcodeDataFormat;
    avro?: AvroDataFormat | string;
    yaml?: YAMLDataFormat;
    fhirJson?: FhirJsonDataFormat;
    any23?: Any23DataFormat | string;
    custom?: CustomDataFormat | string;
    flatpack?: FlatpackDataFormat;
    cbor?: CBORDataFormat;
    crypto?: CryptoDataFormat;
    univocityTsv?: UniVocityTsvDataFormat;
    hl7?: HL7DataFormat;
    jsonApi?: JsonApiDataFormat;
    xmlSecurity?: XMLSecurityDataFormat;
    ical?: IcalDataFormat;
    univocityFixed?: UniVocityFixedDataFormat;
    jacksonXml?: JacksonXMLDataFormat;
    grok?: GrokDataFormat;
    xstream?: XStreamDataFormat | string;
    gzipDeflater?: GzipDeflaterDataFormat;
    soap?: SoapDataFormat | string;
    constructor(init?: Partial<DataFormatsDefinition>);
}
export declare class FhirJsonDataFormat extends CamelElement {
    contentTypeHeader?: boolean;
    dontStripVersionsFromReferencesAtPaths?: string[];
    prettyPrint?: boolean;
    dataFormatName?: string;
    dontEncodeElements?: string[];
    summaryMode?: boolean;
    encodeElementsAppliesToChildResourcesOnly?: boolean;
    serverBaseUrl?: string;
    fhirVersion?: string;
    suppressNarratives?: boolean;
    encodeElements?: string[];
    stripVersionsFromReferences?: boolean;
    id?: string;
    omitResourceId?: boolean;
    overrideResourceIdWithBundleEntryFullUrl?: boolean;
    constructor(init?: Partial<FhirJsonDataFormat>);
}
export declare class FhirXmlDataFormat extends CamelElement {
    contentTypeHeader?: boolean;
    dontStripVersionsFromReferencesAtPaths?: string[];
    prettyPrint?: boolean;
    dataFormatName?: string;
    dontEncodeElements?: string[];
    summaryMode?: boolean;
    encodeElementsAppliesToChildResourcesOnly?: boolean;
    serverBaseUrl?: string;
    fhirVersion?: string;
    suppressNarratives?: boolean;
    encodeElements?: string[];
    stripVersionsFromReferences?: boolean;
    id?: string;
    omitResourceId?: boolean;
    overrideResourceIdWithBundleEntryFullUrl?: boolean;
    constructor(init?: Partial<FhirXmlDataFormat>);
}
export declare class FlatpackDataFormat extends CamelElement {
    allowShortLines?: boolean;
    dataFormatName?: string;
    delimiter?: string;
    definition?: string;
    fixed?: boolean;
    id?: string;
    ignoreFirstRecord?: boolean;
    parserFactoryRef?: string;
    textQualifier?: string;
    ignoreExtraColumns?: boolean;
    constructor(init?: Partial<FlatpackDataFormat>);
}
export declare class GrokDataFormat extends CamelElement {
    flattened?: boolean;
    namedOnly?: boolean;
    dataFormatName?: string;
    pattern: string;
    allowMultipleMatchesPerLine?: boolean;
    id?: string;
    constructor(init?: Partial<GrokDataFormat>);
}
export declare class GzipDeflaterDataFormat extends CamelElement {
    dataFormatName?: string;
    id?: string;
    constructor(init?: Partial<GzipDeflaterDataFormat>);
}
export declare class HL7DataFormat extends CamelElement {
    dataFormatName?: string;
    id?: string;
    validate?: boolean;
    constructor(init?: Partial<HL7DataFormat>);
}
export declare class IcalDataFormat extends CamelElement {
    validating?: boolean;
    dataFormatName?: string;
    id?: string;
    constructor(init?: Partial<IcalDataFormat>);
}
export declare class JacksonXMLDataFormat extends CamelElement {
    allowUnmarshallType?: boolean;
    include?: string;
    contentTypeHeader?: boolean;
    prettyPrint?: boolean;
    jsonView?: string;
    dataFormatName?: string;
    timezone?: string;
    moduleClassNames?: string;
    allowJmsType?: boolean;
    enableFeatures?: string;
    unmarshalType?: string;
    useList?: boolean;
    disableFeatures?: string;
    moduleRefs?: string;
    collectionType?: string;
    id?: string;
    enableJaxbAnnotationModule?: boolean;
    xmlMapper?: string;
    constructor(init?: Partial<JacksonXMLDataFormat>);
}
export declare class JaxbDataFormat extends CamelElement {
    schema?: string;
    contentTypeHeader?: boolean;
    prettyPrint?: boolean;
    dataFormatName?: string;
    contextPathIsClassName?: boolean;
    schemaLocation?: string;
    contextPath: string;
    schemaSeverityLevel?: string;
    xmlStreamWriterWrapper?: string;
    noNamespaceSchemaLocation?: string;
    encoding?: string;
    mustBeJaxbElement?: boolean;
    filterNonXmlChars?: boolean;
    fragment?: boolean;
    objectFactory?: boolean;
    namespacePrefixRef?: string;
    partClass?: string;
    ignoreJaxbElement?: boolean;
    id?: string;
    jaxbProviderProperties?: string;
    partNamespace?: string;
    constructor(init?: Partial<JaxbDataFormat>);
}
export declare class JsonApiDataFormat extends CamelElement {
    dataFormatName?: string;
    id?: string;
    mainFormatType?: string;
    constructor(init?: Partial<JsonApiDataFormat>);
}
export declare class JsonDataFormat extends CamelElement {
    contentTypeHeader?: boolean;
    timezone?: string;
    moduleClassNames?: string;
    allowJmsType?: boolean;
    enableFeatures?: string;
    unmarshalType?: string;
    library?: string;
    permissions?: string;
    autoDiscoverObjectMapper?: boolean;
    id?: string;
    allowUnmarshallType?: boolean;
    include?: string;
    prettyPrint?: boolean;
    jsonView?: string;
    dataFormatName?: string;
    autoDiscoverSchemaResolver?: boolean;
    useList?: boolean;
    disableFeatures?: string;
    moduleRefs?: string;
    schemaResolver?: string;
    collectionType?: string;
    useDefaultObjectMapper?: boolean;
    objectMapper?: string;
    dropRootNode?: boolean;
    namingStrategy?: string;
    constructor(init?: Partial<JsonDataFormat>);
}
export declare class LZFDataFormat extends CamelElement {
    dataFormatName?: string;
    id?: string;
    usingParallelCompression?: boolean;
    constructor(init?: Partial<LZFDataFormat>);
}
export declare class MimeMultipartDataFormat extends CamelElement {
    headersInline?: boolean;
    multipartSubType?: string;
    multipartWithoutAttachment?: boolean;
    dataFormatName?: string;
    id?: string;
    includeHeaders?: string;
    binaryContent?: boolean;
    constructor(init?: Partial<MimeMultipartDataFormat>);
}
export declare class PGPDataFormat extends CamelElement {
    dataFormatName?: string;
    armored?: boolean;
    signaturePassword?: string;
    signatureKeyRing?: string;
    keyFileName?: string;
    signatureVerificationOption?: string;
    signatureKeyUserid?: string;
    integrity?: boolean;
    password?: string;
    provider?: string;
    compressionAlgorithm?: number;
    keyUserid?: string;
    signatureKeyFileName?: string;
    id?: string;
    hashAlgorithm?: number;
    algorithm?: number;
    constructor(init?: Partial<PGPDataFormat>);
}
export declare class ProtobufDataFormat extends CamelElement {
    allowUnmarshallType?: boolean;
    include?: string;
    contentTypeHeader?: boolean;
    contentTypeFormat?: string;
    jsonView?: string;
    dataFormatName?: string;
    autoDiscoverSchemaResolver?: boolean;
    timezone?: string;
    moduleClassNames?: string;
    allowJmsType?: boolean;
    instanceClass?: string;
    enableFeatures?: string;
    unmarshalType?: string;
    useList?: boolean;
    disableFeatures?: string;
    moduleRefs?: string;
    schemaResolver?: string;
    collectionType?: string;
    useDefaultObjectMapper?: boolean;
    library?: string;
    objectMapper?: string;
    autoDiscoverObjectMapper?: boolean;
    id?: string;
    constructor(init?: Partial<ProtobufDataFormat>);
}
export declare class RssDataFormat extends CamelElement {
    dataFormatName?: string;
    id?: string;
    constructor(init?: Partial<RssDataFormat>);
}
export declare class SoapDataFormat extends CamelElement {
    schema?: string;
    namespacePrefixRef?: string;
    dataFormatName?: string;
    elementNameStrategyRef?: string;
    contextPath: string;
    id?: string;
    encoding?: string;
    version?: string;
    constructor(init?: Partial<SoapDataFormat>);
}
export declare class SyslogDataFormat extends CamelElement {
    dataFormatName?: string;
    id?: string;
    constructor(init?: Partial<SyslogDataFormat>);
}
export declare class TarFileDataFormat extends CamelElement {
    maxDecompressedSize?: number;
    dataFormatName?: string;
    usingIterator?: boolean;
    id?: string;
    preservePathElements?: boolean;
    allowEmptyDirectory?: boolean;
    constructor(init?: Partial<TarFileDataFormat>);
}
export declare class ThriftDataFormat extends CamelElement {
    contentTypeHeader?: boolean;
    contentTypeFormat?: string;
    dataFormatName?: string;
    instanceClass?: string;
    id?: string;
    constructor(init?: Partial<ThriftDataFormat>);
}
export declare class TidyMarkupDataFormat extends CamelElement {
    omitXmlDeclaration?: boolean;
    dataObjectType?: string;
    dataFormatName?: string;
    id?: string;
    constructor(init?: Partial<TidyMarkupDataFormat>);
}
export declare class UniVocityCsvDataFormat extends CamelElement {
    headerExtractionEnabled?: boolean;
    skipEmptyLines?: boolean;
    dataFormatName?: string;
    asMap?: boolean;
    ignoreLeadingWhitespaces?: boolean;
    univocityHeader?: UniVocityHeader[];
    ignoreTrailingWhitespaces?: boolean;
    lineSeparator?: string;
    lazyLoad?: boolean;
    nullValue?: string;
    quoteAllFields?: boolean;
    normalizedLineSeparator?: string;
    emptyValue?: string;
    quote?: string;
    quoteEscape?: string;
    delimiter?: string;
    headersDisabled?: boolean;
    comment?: string;
    id?: string;
    numberOfRecordsToRead?: number;
    constructor(init?: Partial<UniVocityCsvDataFormat>);
}
export declare class UniVocityFixedDataFormat extends CamelElement {
    headerExtractionEnabled?: boolean;
    padding?: string;
    recordEndsOnNewline?: boolean;
    skipEmptyLines?: boolean;
    dataFormatName?: string;
    asMap?: boolean;
    ignoreLeadingWhitespaces?: boolean;
    univocityHeader?: UniVocityHeader[];
    ignoreTrailingWhitespaces?: boolean;
    lineSeparator?: string;
    lazyLoad?: boolean;
    nullValue?: string;
    normalizedLineSeparator?: string;
    emptyValue?: string;
    headersDisabled?: boolean;
    comment?: string;
    id?: string;
    numberOfRecordsToRead?: number;
    skipTrailingCharsUntilNewline?: boolean;
    constructor(init?: Partial<UniVocityFixedDataFormat>);
}
export declare class UniVocityHeader extends CamelElement {
    length?: string;
    name?: string;
    constructor(init?: Partial<UniVocityHeader>);
}
export declare class UniVocityTsvDataFormat extends CamelElement {
    escapeChar?: string;
    headerExtractionEnabled?: boolean;
    skipEmptyLines?: boolean;
    dataFormatName?: string;
    asMap?: boolean;
    ignoreLeadingWhitespaces?: boolean;
    univocityHeader?: UniVocityHeader[];
    ignoreTrailingWhitespaces?: boolean;
    lineSeparator?: string;
    lazyLoad?: boolean;
    nullValue?: string;
    normalizedLineSeparator?: string;
    emptyValue?: string;
    headersDisabled?: boolean;
    comment?: string;
    id?: string;
    numberOfRecordsToRead?: number;
    constructor(init?: Partial<UniVocityTsvDataFormat>);
}
export declare class XMLSecurityDataFormat extends CamelElement {
    addKeyValueForEncryptedKey?: boolean;
    keyCipherAlgorithm?: string;
    dataFormatName?: string;
    recipientKeyAlias?: string;
    keyOrTrustStoreParametersRef?: string;
    digestAlgorithm?: string;
    mgfAlgorithm?: string;
    secureTagContents?: boolean;
    passPhraseByte?: string;
    keyPassword?: string;
    secureTag?: string;
    id?: string;
    xmlCipherAlgorithm?: string;
    passPhrase?: string;
    constructor(init?: Partial<XMLSecurityDataFormat>);
}
export declare class XStreamDataFormat extends CamelElement {
    mode?: string;
    omitFields?: PropertyDefinition[];
    aliases?: PropertyDefinition[];
    contentTypeHeader?: boolean;
    driver?: string;
    driverRef?: string;
    implicitCollections?: PropertyDefinition[];
    dataFormatName?: string;
    permissions?: string;
    converters?: PropertyDefinition[];
    id?: string;
    encoding?: string;
    constructor(init?: Partial<XStreamDataFormat>);
}
export declare class YAMLDataFormat extends CamelElement {
    resolver?: string;
    _constructor?: string;
    prettyFlow?: boolean;
    dataFormatName?: string;
    allowAnyType?: boolean;
    representer?: string;
    unmarshalType?: string;
    library?: string;
    typeFilter?: YAMLTypeFilterDefinition[];
    maxAliasesForCollections?: number;
    dumperOptions?: string;
    id?: string;
    useApplicationContextClassLoader?: boolean;
    allowRecursiveKeys?: boolean;
    constructor(init?: Partial<YAMLDataFormat>);
}
export declare class YAMLTypeFilterDefinition extends CamelElement {
    stepName?: string;
    type?: string;
    value?: string;
    constructor(init?: Partial<YAMLTypeFilterDefinition>);
}
export declare class ZipDeflaterDataFormat extends CamelElement {
    dataFormatName?: string;
    id?: string;
    compressionLevel?: string;
    constructor(init?: Partial<ZipDeflaterDataFormat>);
}
export declare class ZipFileDataFormat extends CamelElement {
    maxDecompressedSize?: number;
    dataFormatName?: string;
    usingIterator?: boolean;
    id?: string;
    preservePathElements?: boolean;
    allowEmptyDirectory?: boolean;
    constructor(init?: Partial<ZipFileDataFormat>);
}
export declare class DeadLetterChannelDefinition extends CamelElement {
    executorServiceRef?: string;
    redeliveryPolicy?: RedeliveryPolicyDefinition;
    level?: string;
    loggerRef?: string;
    useOriginalMessage?: boolean;
    deadLetterHandleNewException?: boolean;
    deadLetterUri: string;
    onRedeliveryRef?: string;
    retryWhileRef?: string;
    logName?: string;
    stepName?: string;
    useOriginalBody?: boolean;
    id?: string;
    onPrepareFailureRef?: string;
    onExceptionOccurredRef?: string;
    redeliveryPolicyRef?: string;
    constructor(init?: Partial<DeadLetterChannelDefinition>);
}
export declare class DefaultErrorHandlerDefinition extends CamelElement {
    executorServiceRef?: string;
    redeliveryPolicy?: RedeliveryPolicyDefinition;
    level?: string;
    loggerRef?: string;
    useOriginalMessage?: boolean;
    onRedeliveryRef?: string;
    retryWhileRef?: string;
    logName?: string;
    stepName?: string;
    useOriginalBody?: boolean;
    id?: string;
    onPrepareFailureRef?: string;
    onExceptionOccurredRef?: string;
    redeliveryPolicyRef?: string;
    constructor(init?: Partial<DefaultErrorHandlerDefinition>);
}
export declare class ErrorHandlerRefDefinition extends CamelElement {
    ref: string;
    stepName?: string;
    id?: string;
    constructor(init?: Partial<ErrorHandlerRefDefinition>);
}
export declare class JtaTransactionErrorHandlerDefinition extends CamelElement {
    executorServiceRef?: string;
    redeliveryPolicy?: RedeliveryPolicyDefinition;
    level?: string;
    loggerRef?: string;
    useOriginalMessage?: boolean;
    onRedeliveryRef?: string;
    retryWhileRef?: string;
    logName?: string;
    stepName?: string;
    useOriginalBody?: boolean;
    rollbackLoggingLevel?: string;
    id?: string;
    onPrepareFailureRef?: string;
    transactedPolicyRef?: string;
    onExceptionOccurredRef?: string;
    redeliveryPolicyRef?: string;
    constructor(init?: Partial<JtaTransactionErrorHandlerDefinition>);
}
export declare class NoErrorHandlerDefinition extends CamelElement {
    stepName?: string;
    id?: string;
    constructor(init?: Partial<NoErrorHandlerDefinition>);
}
export declare class SpringTransactionErrorHandlerDefinition extends CamelElement {
    executorServiceRef?: string;
    redeliveryPolicy?: RedeliveryPolicyDefinition;
    level?: string;
    loggerRef?: string;
    useOriginalMessage?: boolean;
    onRedeliveryRef?: string;
    retryWhileRef?: string;
    logName?: string;
    stepName?: string;
    useOriginalBody?: boolean;
    rollbackLoggingLevel?: string;
    id?: string;
    onPrepareFailureRef?: string;
    transactedPolicyRef?: string;
    onExceptionOccurredRef?: string;
    redeliveryPolicyRef?: string;
    constructor(init?: Partial<SpringTransactionErrorHandlerDefinition>);
}
export declare class CSimpleExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    resultType?: string;
    constructor(init?: Partial<CSimpleExpression>);
}
export declare class ConstantExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    resultType?: string;
    constructor(init?: Partial<ConstantExpression>);
}
export declare class DatasonnetExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    outputMediaType?: string;
    id?: string;
    resultType?: string;
    bodyMediaType?: string;
    constructor(init?: Partial<DatasonnetExpression>);
}
export declare class ExchangePropertyExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    constructor(init?: Partial<ExchangePropertyExpression>);
}
export declare class ExpressionDefinition extends CamelElement {
    ognl?: OgnlExpression | string;
    constant?: ConstantExpression | string;
    mvel?: MvelExpression | string;
    method?: MethodCallExpression | string;
    xquery?: XQueryExpression | string;
    datasonnet?: DatasonnetExpression | string;
    jq?: JqExpression | string;
    language?: LanguageExpression;
    simple?: SimpleExpression | string;
    hl7terser?: Hl7TerserExpression | string;
    tokenize?: TokenizerExpression | string;
    spel?: SpELExpression | string;
    ref?: RefExpression | string;
    xpath?: XPathExpression | string;
    groovy?: GroovyExpression | string;
    csimple?: CSimpleExpression | string;
    stepName?: string;
    exchangeProperty?: ExchangePropertyExpression | string;
    jsonpath?: JsonPathExpression | string;
    header?: HeaderExpression | string;
    joor?: JoorExpression | string;
    xtokenize?: XMLTokenizerExpression | string;
    constructor(init?: Partial<ExpressionDefinition>);
}
export declare class GroovyExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    constructor(init?: Partial<GroovyExpression>);
}
export declare class HeaderExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    constructor(init?: Partial<HeaderExpression>);
}
export declare class Hl7TerserExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    constructor(init?: Partial<Hl7TerserExpression>);
}
export declare class JoorExpression extends CamelElement {
    preCompile?: boolean;
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    singleQuotes?: boolean;
    resultType?: string;
    constructor(init?: Partial<JoorExpression>);
}
export declare class JqExpression extends CamelElement {
    expression: string;
    headerName?: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    resultType?: string;
    constructor(init?: Partial<JqExpression>);
}
export declare class JsonPathExpression extends CamelElement {
    expression: string;
    headerName?: string;
    trim?: boolean;
    expressionName?: string;
    writeAsString?: boolean;
    id?: string;
    allowSimple?: boolean;
    suppressExceptions?: boolean;
    allowEasyPredicate?: boolean;
    resultType?: string;
    option?: string;
    constructor(init?: Partial<JsonPathExpression>);
}
export declare class LanguageExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    language: string;
    id?: string;
    constructor(init?: Partial<LanguageExpression>);
}
export declare class MethodCallExpression extends CamelElement {
    ref?: string;
    method?: string;
    trim?: boolean;
    expressionName?: string;
    scope?: string;
    id?: string;
    beanType?: string;
    constructor(init?: Partial<MethodCallExpression>);
}
export declare class MvelExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    constructor(init?: Partial<MvelExpression>);
}
export declare class OgnlExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    constructor(init?: Partial<OgnlExpression>);
}
export declare class RefExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    constructor(init?: Partial<RefExpression>);
}
export declare class SimpleExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    resultType?: string;
    constructor(init?: Partial<SimpleExpression>);
}
export declare class SpELExpression extends CamelElement {
    expression: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    constructor(init?: Partial<SpELExpression>);
}
export declare class TokenizerExpression extends CamelElement {
    endToken?: string;
    headerName?: string;
    skipFirst?: boolean;
    expressionName?: string;
    inheritNamespaceTagName?: string;
    groupDelimiter?: string;
    token: string;
    regex?: boolean;
    includeTokens?: boolean;
    trim?: boolean;
    xml?: boolean;
    id?: string;
    group?: string;
    constructor(init?: Partial<TokenizerExpression>);
}
export declare class XMLTokenizerExpression extends CamelElement {
    mode?: string;
    headerName?: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    group?: number;
    constructor(init?: Partial<XMLTokenizerExpression>);
}
export declare class XPathExpression extends CamelElement {
    preCompile?: boolean;
    expression: string;
    headerName?: string;
    documentType?: string;
    expressionName?: string;
    factoryRef?: string;
    saxon?: boolean;
    trim?: boolean;
    objectModel?: string;
    logNamespaces?: boolean;
    threadSafety?: boolean;
    id?: string;
    resultType?: string;
    constructor(init?: Partial<XPathExpression>);
}
export declare class XQueryExpression extends CamelElement {
    expression: string;
    headerName?: string;
    configurationRef?: string;
    trim?: boolean;
    expressionName?: string;
    id?: string;
    type?: string;
    constructor(init?: Partial<XQueryExpression>);
}
export declare class CustomLoadBalancerDefinition extends CamelElement {
    ref: string;
    stepName?: string;
    id?: string;
    constructor(init?: Partial<CustomLoadBalancerDefinition>);
}
export declare class FailoverLoadBalancerDefinition extends CamelElement {
    exception?: string[];
    stepName?: string;
    sticky?: string;
    id?: string;
    maximumFailoverAttempts?: string;
    roundRobin?: string;
    constructor(init?: Partial<FailoverLoadBalancerDefinition>);
}
export declare class RandomLoadBalancerDefinition extends CamelElement {
    stepName?: string;
    id?: string;
    constructor(init?: Partial<RandomLoadBalancerDefinition>);
}
export declare class RoundRobinLoadBalancerDefinition extends CamelElement {
    stepName?: string;
    id?: string;
    constructor(init?: Partial<RoundRobinLoadBalancerDefinition>);
}
export declare class StickyLoadBalancerDefinition extends CamelElement {
    stepName?: string;
    correlationExpression?: ExpressionSubElementDefinition;
    id?: string;
    constructor(init?: Partial<StickyLoadBalancerDefinition>);
}
export declare class TopicLoadBalancerDefinition extends CamelElement {
    stepName?: string;
    id?: string;
    constructor(init?: Partial<TopicLoadBalancerDefinition>);
}
export declare class WeightedLoadBalancerDefinition extends CamelElement {
    distributionRatioDelimiter?: string;
    stepName?: string;
    id?: string;
    distributionRatio: string;
    roundRobin?: boolean;
    constructor(init?: Partial<WeightedLoadBalancerDefinition>);
}
export declare class ApiKeyDefinition extends CamelElement {
    inHeader?: boolean;
    inCookie?: boolean;
    stepName?: string;
    name: string;
    description?: string;
    inQuery?: boolean;
    key: string;
    constructor(init?: Partial<ApiKeyDefinition>);
}
export declare class BasicAuthDefinition extends CamelElement {
    stepName?: string;
    description?: string;
    key: string;
    constructor(init?: Partial<BasicAuthDefinition>);
}
export declare class BearerTokenDefinition extends CamelElement {
    stepName?: string;
    format?: string;
    description?: string;
    key: string;
    constructor(init?: Partial<BearerTokenDefinition>);
}
export declare class DeleteDefinition extends CamelElement {
    enableCors?: boolean;
    deprecated?: boolean;
    description?: string;
    type?: string;
    outType?: string;
    path?: string;
    security?: SecurityDefinition[];
    bindingMode?: string;
    stepName?: string;
    param?: ParamDefinition[];
    apiDocs?: boolean;
    skipBindingOnErrorCode?: boolean;
    clientRequestValidation?: boolean;
    produces?: string;
    id?: string;
    to?: string;
    responseMessage?: ResponseMessageDefinition[];
    consumes?: string;
    constructor(init?: Partial<DeleteDefinition>);
}
export declare class GetDefinition extends CamelElement {
    enableCors?: boolean;
    deprecated?: boolean;
    description?: string;
    type?: string;
    outType?: string;
    path?: string;
    security?: SecurityDefinition[];
    bindingMode?: string;
    stepName?: string;
    param?: ParamDefinition[];
    apiDocs?: boolean;
    skipBindingOnErrorCode?: boolean;
    clientRequestValidation?: boolean;
    produces?: string;
    id?: string;
    to?: string;
    responseMessage?: ResponseMessageDefinition[];
    consumes?: string;
    constructor(init?: Partial<GetDefinition>);
}
export declare class HeadDefinition extends CamelElement {
    enableCors?: boolean;
    deprecated?: boolean;
    description?: string;
    type?: string;
    outType?: string;
    path?: string;
    security?: SecurityDefinition[];
    bindingMode?: string;
    stepName?: string;
    param?: ParamDefinition[];
    apiDocs?: boolean;
    skipBindingOnErrorCode?: boolean;
    clientRequestValidation?: boolean;
    produces?: string;
    id?: string;
    to?: string;
    responseMessage?: ResponseMessageDefinition[];
    consumes?: string;
    constructor(init?: Partial<HeadDefinition>);
}
export declare class MutualTLSDefinition extends CamelElement {
    stepName?: string;
    description?: string;
    key: string;
    constructor(init?: Partial<MutualTLSDefinition>);
}
export declare class OAuth2Definition extends CamelElement {
    tokenUrl?: string;
    authorizationUrl?: string;
    stepName?: string;
    refreshUrl?: string;
    description?: string;
    scopes?: RestPropertyDefinition[];
    flow?: string;
    key: string;
    constructor(init?: Partial<OAuth2Definition>);
}
export declare class OpenIdConnectDefinition extends CamelElement {
    stepName?: string;
    description?: string;
    key: string;
    url: string;
    constructor(init?: Partial<OpenIdConnectDefinition>);
}
export declare class ParamDefinition extends CamelElement {
    arrayType?: string;
    examples?: RestPropertyDefinition[];
    stepName?: string;
    dataFormat?: string;
    defaultValue?: string;
    dataType?: string;
    name: string;
    description?: string;
    type: string;
    collectionFormat?: string;
    value?: string[];
    required?: boolean;
    constructor(init?: Partial<ParamDefinition>);
}
export declare class PatchDefinition extends CamelElement {
    enableCors?: boolean;
    deprecated?: boolean;
    description?: string;
    type?: string;
    outType?: string;
    path?: string;
    security?: SecurityDefinition[];
    bindingMode?: string;
    stepName?: string;
    param?: ParamDefinition[];
    apiDocs?: boolean;
    skipBindingOnErrorCode?: boolean;
    clientRequestValidation?: boolean;
    produces?: string;
    id?: string;
    to?: string;
    responseMessage?: ResponseMessageDefinition[];
    consumes?: string;
    constructor(init?: Partial<PatchDefinition>);
}
export declare class PostDefinition extends CamelElement {
    enableCors?: boolean;
    deprecated?: boolean;
    description?: string;
    type?: string;
    outType?: string;
    path?: string;
    security?: SecurityDefinition[];
    bindingMode?: string;
    stepName?: string;
    param?: ParamDefinition[];
    apiDocs?: boolean;
    skipBindingOnErrorCode?: boolean;
    clientRequestValidation?: boolean;
    produces?: string;
    id?: string;
    to?: string;
    responseMessage?: ResponseMessageDefinition[];
    consumes?: string;
    constructor(init?: Partial<PostDefinition>);
}
export declare class PutDefinition extends CamelElement {
    enableCors?: boolean;
    deprecated?: boolean;
    description?: string;
    type?: string;
    outType?: string;
    path?: string;
    security?: SecurityDefinition[];
    bindingMode?: string;
    stepName?: string;
    param?: ParamDefinition[];
    apiDocs?: boolean;
    skipBindingOnErrorCode?: boolean;
    clientRequestValidation?: boolean;
    produces?: string;
    id?: string;
    to?: string;
    responseMessage?: ResponseMessageDefinition[];
    consumes?: string;
    constructor(init?: Partial<PutDefinition>);
}
export declare class ResponseHeaderDefinition extends CamelElement {
    arrayType?: string;
    stepName?: string;
    dataFormat?: string;
    dataType?: string;
    name: string;
    description?: string;
    collectionFormat?: string;
    value?: string[];
    example?: string;
    constructor(init?: Partial<ResponseHeaderDefinition>);
}
export declare class ResponseMessageDefinition extends CamelElement {
    code?: string;
    examples?: RestPropertyDefinition[];
    stepName?: string;
    header?: ResponseHeaderDefinition[];
    responseModel?: string;
    message: string;
    constructor(init?: Partial<ResponseMessageDefinition>);
}
export declare class RestBindingDefinition extends CamelElement {
    enableCors?: boolean;
    component?: string;
    bindingMode?: string;
    stepName?: string;
    skipBindingOnErrorCode?: boolean;
    clientRequestValidation?: boolean;
    produces?: string;
    description?: string;
    id?: string;
    type?: string;
    outType?: string;
    consumes?: string;
    constructor(init?: Partial<RestBindingDefinition>);
}
export declare class RestConfigurationDefinition extends CamelElement {
    enableCors?: boolean;
    scheme?: string;
    apiContextPath?: string;
    consumerProperty?: RestPropertyDefinition[];
    apiProperty?: RestPropertyDefinition[];
    hostNameResolver?: string;
    componentProperty?: RestPropertyDefinition[];
    corsHeaders?: RestPropertyDefinition[];
    stepName?: string;
    skipBindingOnErrorCode?: boolean;
    clientRequestValidation?: boolean;
    host?: string;
    producerApiDoc?: string;
    producerComponent?: string;
    endpointProperty?: RestPropertyDefinition[];
    useXForwardHeaders?: boolean;
    apiHost?: string;
    contextPath?: string;
    component?: string;
    dataFormatProperty?: RestPropertyDefinition[];
    bindingMode?: string;
    port?: string;
    xmlDataFormat?: string;
    apiComponent?: string;
    apiVendorExtension?: boolean;
    jsonDataFormat?: string;
    constructor(init?: Partial<RestConfigurationDefinition>);
}
export declare class RestDefinition extends CamelElement {
    enableCors?: boolean;
    securityRequirements?: SecurityDefinition[];
    description?: string;
    delete?: DeleteDefinition[];
    put?: PutDefinition[];
    head?: HeadDefinition[];
    patch?: PatchDefinition[];
    path?: string;
    bindingMode?: string;
    post?: PostDefinition[];
    stepName?: string;
    apiDocs?: boolean;
    skipBindingOnErrorCode?: boolean;
    get?: GetDefinition[];
    clientRequestValidation?: boolean;
    produces?: string;
    id?: string;
    tag?: string;
    securityDefinitions?: RestSecuritiesDefinition;
    consumes?: string;
    constructor(init?: Partial<RestDefinition>);
}
export declare class RestPropertyDefinition extends CamelElement {
    stepName?: string;
    value: string;
    key: string;
    constructor(init?: Partial<RestPropertyDefinition>);
}
export declare class RestSecuritiesDefinition extends CamelElement {
    openIdConnect?: OpenIdConnectDefinition;
    apiKey?: ApiKeyDefinition;
    stepName?: string;
    basicAuth?: BasicAuthDefinition;
    mutualTls?: MutualTLSDefinition;
    bearer?: BearerTokenDefinition;
    oauth2?: OAuth2Definition;
    constructor(init?: Partial<RestSecuritiesDefinition>);
}
export declare class RestsDefinition extends CamelElement {
    rest?: RestDefinition[];
    stepName?: string;
    description?: string;
    id?: string;
    constructor(init?: Partial<RestsDefinition>);
}
export declare class SecurityDefinition extends CamelElement {
    stepName?: string;
    scopes?: string;
    key: string;
    constructor(init?: Partial<SecurityDefinition>);
}
export declare class CustomTransformerDefinition extends CamelElement {
    ref?: string;
    toType?: string;
    fromType?: string;
    scheme?: string;
    stepName?: string;
    className?: string;
    constructor(init?: Partial<CustomTransformerDefinition>);
}
export declare class DataFormatTransformerDefinition extends CamelElement {
    univocityCsv?: UniVocityCsvDataFormat;
    protobuf?: ProtobufDataFormat | string;
    tarFile?: TarFileDataFormat;
    tidyMarkup?: TidyMarkupDataFormat;
    scheme?: string;
    csv?: CsvDataFormat | string;
    base64?: Base64DataFormat;
    zipDeflater?: ZipDeflaterDataFormat;
    bindy?: BindyDataFormat;
    syslog?: SyslogDataFormat;
    zipFile?: ZipFileDataFormat;
    jaxb?: JaxbDataFormat;
    rss?: RssDataFormat;
    fromType?: string;
    stepName?: string;
    mimeMultipart?: MimeMultipartDataFormat;
    asn1?: ASN1DataFormat | string;
    pgp?: PGPDataFormat;
    thrift?: ThriftDataFormat | string;
    json?: JsonDataFormat;
    lzf?: LZFDataFormat;
    fhirXml?: FhirXmlDataFormat;
    barcode?: BarcodeDataFormat;
    avro?: AvroDataFormat | string;
    yaml?: YAMLDataFormat;
    toType?: string;
    fhirJson?: FhirJsonDataFormat;
    any23?: Any23DataFormat | string;
    custom?: CustomDataFormat | string;
    flatpack?: FlatpackDataFormat;
    cbor?: CBORDataFormat;
    crypto?: CryptoDataFormat;
    univocityTsv?: UniVocityTsvDataFormat;
    hl7?: HL7DataFormat;
    jsonApi?: JsonApiDataFormat;
    xmlSecurity?: XMLSecurityDataFormat;
    ical?: IcalDataFormat;
    univocityFixed?: UniVocityFixedDataFormat;
    jacksonXml?: JacksonXMLDataFormat;
    grok?: GrokDataFormat;
    xstream?: XStreamDataFormat | string;
    gzipDeflater?: GzipDeflaterDataFormat;
    soap?: SoapDataFormat | string;
    constructor(init?: Partial<DataFormatTransformerDefinition>);
}
export declare class EndpointTransformerDefinition extends CamelElement {
    ref?: string;
    toType?: string;
    fromType?: string;
    scheme?: string;
    stepName?: string;
    uri?: string;
    constructor(init?: Partial<EndpointTransformerDefinition>);
}
export declare class TransformersDefinition extends CamelElement {
    endpointTransformer?: EndpointTransformerDefinition;
    customTransformer?: CustomTransformerDefinition;
    stepName?: string;
    dataFormatTransformer?: DataFormatTransformerDefinition;
    constructor(init?: Partial<TransformersDefinition>);
}
export declare class CustomValidatorDefinition extends CamelElement {
    ref?: string;
    stepName?: string;
    className?: string;
    type?: string;
    constructor(init?: Partial<CustomValidatorDefinition>);
}
export declare class EndpointValidatorDefinition extends CamelElement {
    ref?: string;
    stepName?: string;
    type?: string;
    uri?: string;
    constructor(init?: Partial<EndpointValidatorDefinition>);
}
export declare class PredicateValidatorDefinition extends CamelElement {
    expression?: ExpressionDefinition;
    stepName?: string;
    type?: string;
    constructor(init?: Partial<PredicateValidatorDefinition>);
}
export declare class ValidatorsDefinition extends CamelElement {
    stepName?: string;
    predicateValidator?: PredicateValidatorDefinition;
    endpointValidator?: EndpointValidatorDefinition;
    customValidator?: CustomValidatorDefinition;
    constructor(init?: Partial<ValidatorsDefinition>);
}
